id: I24B512F6
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T14:34:03.399776'
last_modified: '2022-06-19T14:34:03.399825'
parser: null
source_metadata:
  title: Hagiography of rJe btsun grags pa rgyal mtshan (1147-1216), no. II; Lamdre
    Lobshe, vol. ka, title no. 6, from the chronological biographies of the Lamdre
    lineage masters
  author: སྦལ་སྟོན་སེང་གེ་རྒྱལ་མཚན།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-16);
    converted from external file, unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/183
  bases:
    bdb4:
      title: Hagiography of rJe btsun grags pa rgyal mtshan (1147-1216), no. II; Lamdre
        Lobshe, vol. ka, title no. 6, from the chronological biographies of the Lamdre
        lineage masters
      order: 1
      base_file: bdb4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
